In [32]:
import numpy as np
a = np.array([[1,2,3],[2,5,6],[6,7,8]])

In [36]:
type(a[1][2])

numpy.int32

In [29]:
a.shape

(1, 3, 3)

In [35]:
a[1][0]

2

In [20]:
type(a[0])

numpy.ndarray

In [23]:
a

array([[1, 2, 3],
       [2, 5, 6]])

In [47]:
a = np.zeros((4,5))
b = np.random.randn(4,5)
print(b)
np.round(b,2,a)

[[ 0.77758742 -1.51092493 -1.02912717  0.15503532 -0.75181707]
 [ 1.59434654 -0.77872701 -0.43314806 -1.10231183  1.56365012]
 [ 0.28057971  0.37595288 -1.06634468 -0.74311538  0.64964376]
 [ 1.65735464  1.28005639 -2.85793178  0.40303318  0.57758462]]


array([[ 0.78, -1.51, -1.03,  0.16, -0.75],
       [ 1.59, -0.78, -0.43, -1.1 ,  1.56],
       [ 0.28,  0.38, -1.07, -0.74,  0.65],
       [ 1.66,  1.28, -2.86,  0.4 ,  0.58]])

In [48]:
a

array([[ 0.78, -1.51, -1.03,  0.16, -0.75],
       [ 1.59, -0.78, -0.43, -1.1 ,  1.56],
       [ 0.28,  0.38, -1.07, -0.74,  0.65],
       [ 1.66,  1.28, -2.86,  0.4 ,  0.58]])

In [49]:
b

array([[ 0.77758742, -1.51092493, -1.02912717,  0.15503532, -0.75181707],
       [ 1.59434654, -0.77872701, -0.43314806, -1.10231183,  1.56365012],
       [ 0.28057971,  0.37595288, -1.06634468, -0.74311538,  0.64964376],
       [ 1.65735464,  1.28005639, -2.85793178,  0.40303318,  0.57758462]])

In [40]:
np.random.randint(10,100,(6,5))

array([[57, 11, 99, 15, 95],
       [44, 59, 35, 22, 17],
       [67, 62, 57, 29, 93],
       [52, 67, 13, 15, 26],
       [32, 17, 18, 78, 43],
       [44, 54, 71, 62, 50]])

In [50]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'Bytes0',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'Datetime64',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Str0',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'Uint64',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',


In [52]:
np.arange(4,20,4)

array([ 4,  8, 12, 16])

In [53]:
np.linspace(4,20,4)

array([ 4.        ,  9.33333333, 14.66666667, 20.        ])

In [55]:
a.ndim

2

In [58]:
a.shape[1]

5

In [62]:
a

array([[ 0.78, -1.51, -1.03,  0.16, -0.75],
       [ 1.59, -0.78, -0.43, -1.1 ,  1.56],
       [ 0.28,  0.38, -1.07, -0.74,  0.65],
       [ 1.66,  1.28, -2.86,  0.4 ,  0.58]])

In [66]:
np.reshape(a,(5,4))

array([[ 0.78, -1.51, -1.03,  0.16],
       [-0.75,  1.59, -0.78, -0.43],
       [-1.1 ,  1.56,  0.28,  0.38],
       [-1.07, -0.74,  0.65,  1.66],
       [ 1.28, -2.86,  0.4 ,  0.58]])

In [68]:
a[2][3] = 100

In [69]:
a

array([[  0.78,  -1.51,  -1.03,   0.16,  -0.75],
       [  1.59,  -0.78,  -0.43,  -1.1 ,   1.56],
       [  0.28,   0.38,  -1.07, 100.  ,   0.65],
       [  1.66,   1.28,  -2.86,   0.4 ,   0.58]])

In [70]:
a.transpose()

array([[  0.78,   1.59,   0.28,   1.66],
       [ -1.51,  -0.78,   0.38,   1.28],
       [ -1.03,  -0.43,  -1.07,  -2.86],
       [  0.16,  -1.1 , 100.  ,   0.4 ],
       [ -0.75,   1.56,   0.65,   0.58]])

In [76]:
a[:3, :3]

array([[ 0.78, -1.51, -1.03],
       [ 1.59, -0.78, -0.43],
       [ 0.28,  0.38, -1.07]])

In [82]:
a = np.random.randn(2,3)
b = np.random.randn(2,4)
np.hstack((a,b))

array([[-0.63114292, -0.50470837, -1.0183248 , -0.75284564,  1.723689  ,
         0.57128207, -1.42949577],
       [-0.24963924,  0.72106576,  0.37913025,  0.82098909,  0.64654651,
        -1.41383084, -0.31394096]])

In [ ]:
np.concatenate

In [91]:
import pandas as pd
import numpy

In [93]:
a = numpy.arange(10,20,2)
b = np.array([[5],[3]])
a+b

array([[15, 17, 19, 21, 23],
       [13, 15, 17, 19, 21]])

In [85]:
a

array([10, 12, 14, 16, 18])

In [88]:
b.shape

(2, 1)

In [90]:
b

array([[2],
       [3]])

In [94]:
l1 = [10,20,30]
l1[0]

10

In [99]:
l2 =[123,125,126]
label = ['day1', 'dau2', 'day3']
s1 = pd.Series(l2, label)
s1

day1    123
dau2    125
day3    126
dtype: int64

In [96]:
s1['dau2']

125

In [97]:
s1[1]

125

In [102]:

data = np.round(np.random.randn(3,5),4)
df = pd.DataFrame(data, ['x1', 'x2', 'x3'], ['A', 'B', 'C', 'D', 'E'])

In [103]:
df

A       B       C       D       E
x1 -1.8266  1.8275 -0.7990  0.3260  1.8521
x2  0.5583  0.1939  0.6801  0.0641  0.4169
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [119]:
df[['A','C']].iloc[0]

A   -1.8266
C   -0.7990
Name: x1, dtype: float64

In [108]:
a1 = df['A']
type(a1)

pandas.core.series.Series

In [109]:
a1 = df[['A']]
type(a1)

pandas.core.frame.DataFrame

In [111]:
df['new'] = df['A'] *df['B']
df

A       B       C       D       E       new
x1 -1.8266  1.8275 -0.7990  0.3260  1.8521 -3.338111
x2  0.5583  0.1939  0.6801  0.0641  0.4169  0.108254
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733 -0.106145

In [122]:
df.drop('new', axis =1, inplace=True)

KeyError: "['new'] not found in axis"

In [123]:
list1 = ['A', 'B', 'C']
df[list1]

A       B       C
x1 -1.8266  1.8275 -0.7990
x2  0.5583  0.1939  0.6801
x3 -0.3121  0.3401  0.6877

In [132]:
df.iloc[:, 0:3]

A       B       C
x1 -1.8266  1.8275 -0.7990
x2  0.5583  0.1939  0.6801
x3 -0.3121  0.3401  0.6877

In [134]:
df.loc['x2':'x3','A':'C']

A       B       C
x2  0.5583  0.1939  0.6801
x3 -0.3121  0.3401  0.6877

In [135]:
df

A       B       C       D       E
x1 -1.8266  1.8275 -0.7990  0.3260  1.8521
x2  0.5583  0.1939  0.6801  0.0641  0.4169
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [144]:
df[(df['C']>0.2) & (df['E']>0.5)]

A       B       C       D       E
x3 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [139]:
df['D']>0.2

x1     True
x2    False
x3    False
Name: D, dtype: bool

In [146]:
df = pd.DataFrame(data,columns = ['A', 'B', 'C', 'D', 'E'])
df

A       B       C       D       E
0 -1.8266  1.8275 -0.7990  0.3260  1.8521
1  0.5583  0.1939  0.6801  0.0641  0.4169
2 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [150]:
df[(df['C']>0.2)].reset_index(drop=True)

A       B       C       D       E
0  0.5583  0.1939  0.6801  0.0641  0.4169
1 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [156]:
df.columns = list(np.arange(1,6))
df

1       2       3       4       5
0 -1.8266  1.8275 -0.7990  0.3260  1.8521
1  0.5583  0.1939  0.6801  0.0641  0.4169
2 -0.3121  0.3401  0.6877 -0.4008  0.5733

In [159]:
b = list(np.arange(1,6))

In [160]:
a =['Name']*5

In [163]:
np.concatenate((a,b))

array(['Name', 'Name', 'Name', 'Name', 'Name', '1', '2', '3', '4', '5'],
      dtype='<U11')

In [164]:
df = pd.DataFrame(np.array([[1, 5, 1],[2, np.nan, 2],[np.nan, np.nan, 3]]))

df.columns = ['A', 'B', 'C']

df

A    B    C
0  1.0  5.0  1.0
1  2.0  NaN  2.0
2  NaN  NaN  3.0

In [165]:
df.fillna(0)

A    B    C
0  1.0  5.0  1.0
1  2.0  0.0  2.0
2  0.0  0.0  3.0

In [166]:
df.mean()

A    1.5
B    5.0
C    2.0
dtype: float64

In [172]:
df.fillna(df.mean(axis =1))

A    B    C
0  1.0  5.0  1.0
1  2.0  NaN  2.0
2  NaN  NaN  3.0

In [169]:
df['A'].fillna(2)

0    1.0
1    2.0
2    2.0
Name: A, dtype: float64

In [174]:
df.fillna(df.mean())

A    B    C
0  1.0  5.0  1.0
1  2.0  5.0  2.0
2  1.5  5.0  3.0

In [175]:
df.mean(axis =0)

A    1.5
B    5.0
C    2.0
dtype: float64

In [ ]:
np.mean()

In [184]:
df = pd.DataFrame([ ['Google','india', 'Sam', 200, 100],

                    ['Google','india', 'Charlie', 120,10],

                    ['Salesforce','US','Ralph', 125,40],

                    ['Salesforce','india','Emily', 250, 60],

                    ['Adobe','UK','Rosalynn', 150, 80],

                    ['Adobe','US','Chelsea', 500, 90]])

df.columns = ['Organization', 'Country','Salesperson Name', 'Sales', 'bonus']

df


Organization Country Salesperson Name  Sales  bonus
0       Google   india              Sam    200    100
1       Google   india          Charlie    120     10
2   Salesforce      US            Ralph    125     40
3   Salesforce   india            Emily    250     60
4        Adobe      UK         Rosalynn    150     80
5        Adobe      US          Chelsea    500     90

In [196]:
df.groupby(['Organization','Country'])['Sales'].agg([sum, np.mean, np.median])

sum   mean  median
Organization Country                    
Adobe        UK       150  150.0   150.0
             US       500  500.0   500.0
Google       india    320  160.0   160.0
Salesforce   US       125  125.0   125.0
             india    250  250.0   250.0

In [186]:
df.groupby(['Organization'])['Sales'].describe()

count   mean         std    min     25%    50%     75%    max
Organization                                                               
Adobe           2.0  325.0  247.487373  150.0  237.50  325.0  412.50  500.0
Google          2.0  160.0   56.568542  120.0  140.00  160.0  180.00  200.0
Salesforce      2.0  187.5   88.388348  125.0  156.25  187.5  218.75  250.0

In [203]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],

                        'B': ['B0', 'B1', 'B2', 'B3'],

                        'C': ['C0', 'C1', 'C2', 'C3'],

                        'D': ['D0', 'D1', 'D2', 'D3']},

                       )

df2 = pd.DataFrame({'A1': ['A4', 'A5', 'A6', 'A7'],

                        'B2': ['B4', 'B5', 'B6', 'B7'],

                        'C2': ['C4', 'C5', 'C6', 'C7'],

                        'D2': ['D4', 'D5', 'D6', 'D7']},

                         ) 

df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],

                        'B': ['B8', 'B9', 'B10', 'B11'],

                        'C': ['C8', 'C9', 'C10', 'C11'],

                        'D': ['D8', 'D9', 'D10', 'D11']},

                       )

In [201]:
pd.concat([df1,df2,df3])

A    B    C    D   D1
0   A0   B0   C0   D0  NaN
1   A1   B1   C1   D1  NaN
2   A2   B2   C2   D2  NaN
3   A3   B3   C3   D3  NaN
0   A4   B4   C4  NaN   D4
1   A5   B5   C5  NaN   D5
2   A6   B6   C6  NaN   D6
3   A7   B7   C7  NaN   D7
0   A8   B8   C8   D8  NaN
1   A9   B9   C9   D9  NaN
2  A10  B10  C10  D10  NaN
3  A11  B11  C11  D11  NaN

In [204]:
pd.concat([df1,df2,df3],axis =1)

A   B   C   D  A1  B2  C2  D2    A    B    C    D
0  A0  B0  C0  D0  A4  B4  C4  D4   A8   B8   C8   D8
1  A1  B1  C1  D1  A5  B5  C5  D5   A9   B9   C9   D9
2  A2  B2  C2  D2  A6  B6  C6  D6  A10  B10  C10  D10
3  A3  B3  C3  D3  A7  B7  C7  D7  A11  B11  C11  D11

In [220]:
df1 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K3'],

                     'A': ['A0', 'A1', 'A2', 'A3'],

                     'B': ['B0', 'B1', 'B2', 'B3']})

   

df2 = pd.DataFrame({'key': ['K0', 'K1', 'K2', 'K4'],

                          'A': ['C0', 'C1', 'C2', 'C3'],

                          'B': ['D0', 'D1', 'D2', 'D3']})  


In [214]:
df1

key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

In [215]:
df2

key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K4  C3  D3

In [221]:
pd.merge(df1,df2,on = 'key', how = 'right')

key  A_x  B_x A_y B_y
0  K0   A0   B0  C0  D0
1  K1   A1   B1  C1  D1
2  K2   A2   B2  C2  D2
3  K4  NaN  NaN  C3  D3

In [223]:
df['Sales'] = pd.to_numeric(df['Sales'])

In [224]:
df

Organization Country Salesperson Name  Sales  bonus
0       Google   india              Sam    200    100
1       Google   india          Charlie    120     10
2   Salesforce      US            Ralph    125     40
3   Salesforce   india            Emily    250     60
4        Adobe      UK         Rosalynn    150     80
5        Adobe      US          Chelsea    500     90

In [227]:
df['Sales'].value_counts()

200    1
120    1
125    1
250    1
150    1
500    1
Name: Sales, dtype: int64

In [228]:
df1 = pd.DataFrame({'key': ['K1', 'K1', 'K2', np.nan],

                     'A': ['A0', 'A1', 'A2', 'A3'],

                     'B': ['B0', 'B1', 'B2', 'B3']})

In [229]:
df1

key   A   B
0   K1  A0  B0
1   K1  A1  B1
2   K2  A2  B2
3  NaN  A3  B3

In [231]:
df1['key'].value_counts()

K1    2
K2    1
Name: key, dtype: int64

In [233]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   key     3 non-null      object
 1   A       4 non-null      object
 2   B       4 non-null      object
dtypes: object(3)
memory usage: 224.0+ bytes


In [235]:
df1.isna().sum()

key    1
A      0
B      0
dtype: int64

In [237]:
np.nan

nan

In [248]:
def f1(x):
    a = x**2
    b = a+100
    d = b /10
    return a,b,d

df['Sales_new'] = df['bonus'].apply(f1)
df

Organization Country Salesperson Name  Sales  bonus               Sales_new  \
0       Google   india              Sam    200    100  (10000, 10100, 1010.0)   
1       Google   india          Charlie    120     10        (100, 200, 20.0)   
2   Salesforce      US            Ralph    125     40     (1600, 1700, 170.0)   
3   Salesforce   india            Emily    250     60     (3600, 3700, 370.0)   
4        Adobe      UK         Rosalynn    150     80     (6400, 6500, 650.0)   
5        Adobe      US          Chelsea    500     90     (8100, 8200, 820.0)   

   Sales_new1  
0       40000  
1       14400  
2       15625  
3       62500  
4       22500  
5      250000

In [244]:
df['Sales_new1'] = df['Sales']**2
df

Organization Country Salesperson Name  Sales  bonus  Sales_new  Sales_new1
0       Google   india              Sam    200    100     4010.0       40000
1       Google   india          Charlie    120     10     1450.0       14400
2   Salesforce      US            Ralph    125     40     1572.5       15625
3   Salesforce   india            Emily    250     60     6260.0       62500
4        Adobe      UK         Rosalynn    150     80     2260.0       22500
5        Adobe      US          Chelsea    500     90    25010.0      250000

In [243]:
f1(120)

1450.0

In [249]:
pwd

'C:\\Users\\Neha\\Documents\\ExcelR_batch_material\\DS_course_material\\Python_for_DS\\Day9_10'

In [255]:
df = pd.read_csv('data/data_clean.csv')

In [257]:
df.columns = ['new','Ozone', 'Solar.R', 'Wind', 'Temp C', 'Month', 'Day',
       'Year', 'Temp', 'Weather']

In [258]:
df

new  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
0      1   41.0    190.0   7.4     67     5    1  2010    67       S
1      2   36.0    118.0   8.0     72     5    2  2010    72       C
2      3   12.0    149.0  12.6     74     5    3  2010    74      PS
3      4   18.0    313.0  11.5     62     5    4  2010    62       S
4      5    NaN      NaN  14.3     56     5    5  2010    56       S
..   ...    ...      ...   ...    ...   ...  ...   ...   ...     ...
153  154   41.0    190.0   7.4     67     5    1  2010    67       C
154  155   30.0    193.0   6.9     70     9   26  2010    70      PS
155  156    NaN    145.0  13.2     77     9   27  2010    77       S
156  157   14.0    191.0  14.3     75     9   28  2010    75       S
157  158   18.0    131.0   8.0     76     9   29  2010    76       C

[158 rows x 10 columns]

In [259]:
pd.read_excel('data/excel.xlsx')

Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [261]:
df.to_csv('test.csv', index=False)

In [263]:
df[153:]

new  Ozone  Solar.R  Wind Temp C Month  Day  Year  Temp Weather
153  154   41.0    190.0   7.4     67     5    1  2010    67       C
154  155   30.0    193.0   6.9     70     9   26  2010    70      PS
155  156    NaN    145.0  13.2     77     9   27  2010    77       S
156  157   14.0    191.0  14.3     75     9   28  2010    75       S
157  158   18.0    131.0   8.0     76     9   29  2010    76       C

In [ ]:
pd.read_sql_query